'use strict';

export const CONTACTS_LOAD_ALL = 'CONTACTS:LOAD:ALL';
export const CONTACTS_LOAD_ONE = 'CONTACTS_LOAD_ONE';
export const CONTACTS_CREATE = 'CONTACTS:CREATE';
export const CONTACTS_EDIT = 'CONTACTS:EDIT';
export const CONTACTS_SAVE = 'CONTACTS:SAVE';
export const CONTACTS_DELETE = 'CONTACTS:DELETE';
export const ROUTE_SET = 'ROUTE:SET';
export const NAVIGATE = 'ROUTE:NAVIGATE';
